/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_frameconstruct_ndk_NdkMethod */

#ifndef _Included_com_frameconstruct_ndk_NdkMethod
#define _Included_com_frameconstruct_ndk_NdkMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_frameconstruct_ndk_NdkMethod
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_frameconstruct_ndk_NdkMethod_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
